### ISSUE TITLE
Display a notice to site administrators if plugin does not meet minimum PHP requirements

### ISSUE THREAD

**Issue by niallkennedy** [twitter/wordpress#6]
Add a visual indication of purposeful non-execution of the plugin for WordPress administrators who have installed and activated the plugin on a server which does not meet the plugin's minimum PHP requirements.

## The issue

The plugin requires PHP 5.4. The plugin loader currently stops loading plugin files and triggers an `E_USER_NOTICE` with a compatibility notice if the plugin executes in with a PHP version before 5.4.

The plugin short description and long description both note the PHP 5.4 requirement. [WordPress supports PHP 5.2.4 or greater](https://wordpress.org/about/requirements/). Plugins are able to specify a range of WordPress releases of known compatibility: a minimum supported version specified by `Requires at least` up to the maximum known compatibility of `Tested up to`. Plugins are not able to list other compatibility requirements programmatically.

It is possible some WordPress sites may install and activate the plugin without meeting the plugin's minimum requirements. The described functionality of the plugin will not function: no settings menu, no shortcode handlers, etc. The person installing the plugin may blame the plugin without understanding the minimum requirements needed for plugin execution.

### Admin notice

The plugin may display a notice to a WordPress user with `manage_plugins` viewing the WordPress administrative interface or just the plugins listing page. WordPress Core displays an update nag with a warning-level highlight in yellow. An error-level highlight may make sense to draw attention to the likely just-executed action of plugin activation.

### Plugin listing

The plugin listing row could display additional information about the plugin state while the plugin is activated. A site administrator would be able to see an incompatibility warning alongside the plugin listing wherever it appears.

## Additional considerations

The plugin can self deactivate if the minimum requirements are not met. The site administrator would see no new messages about incompatibility until the plugin is reactivated.

A message or possible notice should not be output during an Ajax request at the risk of breaking the expected format of the response.

**Comment by coenjacobs** [comment]
Hey @niallkennedy, I've mentioned this in the other pull request as well. Figured I'd raise it here as well, as I think this is a perfect fit for the project. I'm glad you require a more modern PHP version. Some feedback to the user who activates the plugin is really needed indeed. With [WPupdatePHP](https://github.com/WPupdatePHP/wp-update-php), this is exactly what I've been trying to achieve for WordPress plugins who want to bump the minimum PHP version.

An important step in this all is education for the end user who sees that notice, which is the other half of the WPupdatePHP project: [the website](http://www.wpupdatephp.com/contact-host/). Since most people seeing this notice have no idea what PHP even is (they run on stone age versions), I think it's really import to give them some more to work with. So on the website, we explain how the user should go about getting their hosting package updated to a more modern PHP version.

If you want, I could setup a pull request to show how I'd implement this, but it's fairly straight forward.
